
project_id = "urlfazjsudkrshanucff"

[functions.fetchUtilityData]
verify_jwt = true

[functions.fetchCarbonIntensity]
verify_jwt = true

[functions.generateRecommendations]
verify_jwt = true

[functions.checkPaymentHistory]
verify_jwt = true
