// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urlfazjsudkrshanucff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVybGZhempzdWRrcnNoYW51Y2ZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMDIwMzIsImV4cCI6MjA2MDg3ODAzMn0.Lviolm--FDzAaaZA-riH7wQ7G_Cwx2lTs-PXzDCFKjk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);